### ISSUE TITLE
Doesn't work on IE 11 - invalid property value

### ISSUE THREAD

**Issue by c00kiemon5ter** [soundblogs/react-soundplayer#61]
Hi there, I've already looked at #53 and there are still problems with IE 11. 
I think this is a different problem, so I made this a separate issue.

On http://labs.voronianski.com/react-soundplayer/#ExamplePlayers IE 11 console outputs
```
SCRIPT380: Invalid property value.
bundle.min.js (23,5634)
```

On my site (with debugging enabled) I get
```
request failed Error: Invalid property value.
   "request failed"
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid property value.",
      message: "Invalid property value.",
      name: "Error",
      number: -2146827908,
      stack: "Error: Invalid property value.
   at SoundCloud.prototype._jsonp (http://10.0.2.2:3000/bundle.js:78193:6)
   at SoundCloud.prototype.resolve (http://10.0.2.2:3000/bundle.js:78155:6)
   at requestAudio (http://10.0.2.2:3000/bundle.js:77992:22)
   at componentDidMount (http://10.0.2.2:3000/bundle.js:77969:18)
   at Anonymous function (http://10.0.2.2:3000/bundle.js:23415:14)
   at measureLifeCyclePerf (http://10.0.2.2:3000/bundle.js:23225:6)
   at Anonymous function (http://10.0.2.2:3000/bundle.js:23414:12)
   at notifyAll (http://10.0.2.2:3000/bundle.js:15771:10)
   at ON_DOM_READY_QUEUEING.close (http://10.0.2.2:3000/bundle.js:26144:6)
   at Mixin.closeAll (http://10.0.2.2:3000/bundle.js:16942:12)"
   }
```

I am using react-soundplayer 1.0.0-rc4 and soundcloud-audio 1.0.4

Do you have any ideas I could test?

**Comment by voronianski** [comment]
Related to https://github.com/voronianski/soundcloud-audio.js/issues/10, should be fixed already.
